# data parameters
dataset_name: dataset
train_data_path: /home/yoon/DF_dataset
dataset_paths: {
  'GAN': 'GAN',
#  'N_GAN': 'N_GAN',
  'Original': 'Original'
}
save_path: checkpoint/conf_train/
resume: False
model_name: xception
num_classes: 2
epoch: 10
batch_size: 8
coder: N9
# training parameters
cuda: True
gpu_ids: [0]  # set the GPU ids to use, e.g. [0] or [1, 2]
num_workers: 16
lr: 0.0002
beta1: 0.9
beta2: 0.999
e: 1e-08
print_iter: 1000
# test parameters
load_path: checkpoint/conf_train/5.tar