# data parameters
dataset_name: ALL_less_data
data_with_subfolder: False
train_data_path: /home/yoon/DF_dataset
dataset_paths: {
  'GAN': 'GAN',
#  'N_GAN': 'N_GAN',
  'Original': 'Original'}
save_path: "checkpoint/ALL_less_train/"
resume: False
model_name: xception
num_classes: 2
epoch: 15
batch_size: 8
margin: [0, 0]
save_image: 500
mask_batch_same: False
coder: Jungmin
# training parameters
expname: deepfake_detection
cuda: True
gpu_ids: [0]  # set the GPU ids to use, e.g. [0] or [1, 2]
num_workers: 16
lr: 0.0002
beta1: 0.9
beta2: 0.999
e: 1e-08
print_iter: 100
viz_iter: 50
viz_max_out: 16
snapshot_save_iter: 20000