# data parameters
dataset_name: GN_data
data_with_subfolder: False
train_data_path: /home/yoon/DF_dataset_downscaled
#train_data_path: /home/yoon/PycharmProjects/MoveData/dfdc_train_sample/faces
dataset_paths: {
  'GAN': 'GAN',
  'N_GAN': 'N_GAN',
  'Original': 'Original'}
#dataset_paths: {
#  "REAL": "REAL",
#  "FAKE": "FAKE"}
save_path: "checkpoint/GN_train/"
resume: False
model_name: xception
num_classes: 2
epoch: 10
batch_size: 8
margin: [0, 0]
save_image: 500
mask_batch_same: False
coder: Jungmin
# training parameters
expname: deepfake_detection
cuda: True
gpu_ids: [0]  # set the GPU ids to use, e.g. [0] or [1, 2]
num_workers: 16
lr: 0.0002
beta1: 0.9
beta2: 0.999
e: 1e-08
print_iter: 100
viz_iter: 50
viz_max_out: 16
snapshot_save_iter: 20000